/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntryNewRouteImport } from './routes/entry/new'
import { Route as FoodNewRouteImport } from './routes/food/new'
import { Route as FoodIdEditRouteImport } from './routes/food/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryNewRoute = EntryNewRouteImport.update({
  id: '/entry/new',
  path: '/entry/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodNewRoute = FoodNewRouteImport.update({
  id: '/food/new',
  path: '/food/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIdEditRoute = FoodIdEditRouteImport.update({
  id: '/food/$id/edit',
  path: '/food/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/entry/new': typeof EntryNewRoute
  '/food/new': typeof FoodNewRoute
  '/food/$id/edit': typeof FoodIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/entry/new': typeof EntryNewRoute
  '/food/new': typeof FoodNewRoute
  '/food/$id/edit': typeof FoodIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/entry/new': typeof EntryNewRoute
  '/food/new': typeof FoodNewRoute
  '/food/$id/edit': typeof FoodIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/foods'
    | '/login'
    | '/entry/new'
    | '/food/new'
    | '/food/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/foods'
    | '/login'
    | '/entry/new'
    | '/food/new'
    | '/food/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/foods'
    | '/login'
    | '/entry/new'
    | '/food/new'
    | '/food/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FoodsRoute: typeof FoodsRoute
  LoginRoute: typeof LoginRoute
  EntryNewRoute: typeof EntryNewRoute
  FoodNewRoute: typeof FoodNewRoute
  FoodIdEditRoute: typeof FoodIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/new': {
      id: '/entry/new'
      path: '/entry/new'
      fullPath: '/entry/new'
      preLoaderRoute: typeof EntryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/new': {
      id: '/food/new'
      path: '/food/new'
      fullPath: '/food/new'
      preLoaderRoute: typeof FoodNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$id/edit': {
      id: '/food/$id/edit'
      path: '/food/$id/edit'
      fullPath: '/food/$id/edit'
      preLoaderRoute: typeof FoodIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FoodsRoute: FoodsRoute,
  LoginRoute: LoginRoute,
  EntryNewRoute: EntryNewRoute,
  FoodNewRoute: FoodNewRoute,
  FoodIdEditRoute: FoodIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
